Repository JOHNKIM-KK/Modu-TodoList, pull requests merged in 2021-08, with the labels that each got.

#5 Feat:디렉터리 세팅 및 Constants 생성(#4)
  .github/ISSUE_TEMPLATE/feature_request.md
  .prettierrc
  src/App.tsx
  src/Components/DragDrop/DragDrop.tsx
  src/Components/DragDrop/index.tsx
  src/Components/Nav/Nav.tsx
  src/Components/Nav/index.tsx
  src/Components/TodoList/TodoCreate.tsx
  src/Components/TodoList/TodoFilter.tsx
  src/Components/TodoList/TodoItem.tsx
  src/Components/TodoList/TodoList.tsx
  src/Components/TodoList/Utils/TodoService.tsx
  src/Components/TodoList/index.tsx
  src/Pages/Home.tsx
  src/Pages/index.tsx
  src/Styles/GlobalStyle.ts
  src/Styles/Theme.ts
  src/Styles/index.tsx
  src/Styles/styled.d.ts
  src/Utils/Constants/Constants.tsx
  src/Utils/Constants/MockUp.tsx
  src/Utils/Constants/Storage.tsx
  src/Utils/Constants/TodoStatus.tsx
  src/Utils/index.tsx
  src/components/.gitkeep
  src/pages/.gitkeep
  src/utils/.gitkeep
  src/utils/Constants/.gitkeep
Labels: Feat

#7 Bug/fix capital error
  .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  src/Components/TodoList/Utils/TodoService.tsx
  src/Utils/Constants/Constants.tsx
  src/Utils/index.tsx
Labels: Fix

#10 Feat: Nav 레이아웃 구현 및 기능 구현
  public/index.html
  src/Components/Nav/Nav.tsx
  src/Pages/Home.tsx
  src/hooks/useInterval.js
Labels: Status: Review 요청

#11 Feat/todo form
  package.json
  public/index.html
  src/Assets/note.png
  src/Assets/note1.png
  src/Assets/note2.jpg
  src/Assets/pngegg.png
  src/Components/TodoList/TodoCreate.tsx
  src/Components/TodoList/TodoFilter.tsx
  src/Components/TodoList/TodoItem.tsx
  src/Components/TodoList/TodoList.tsx
  src/Components/TodoList/Utils/TodoService.tsx
  src/Layouts/TodoTemplate.tsx
  src/Layouts/index.tsx
  src/Pages/Home.tsx
  src/Styles/Theme.ts
  src/Styles/styled.d.ts
  src/Utils/Constants/TodoStatus.tsx
  src/styles/Theme.ts
  src/styles/styled.d.ts
  yarn.lock
Labels: Feat, Status: 수정 요청

#14 Feat: create To do Item(#13)
  src/Components/TodoList/TodoCreate.tsx
  src/Components/TodoList/Utils/TodoService.tsx
  src/Components/TodoList/index.tsx
  src/Layouts/TodoTemplate.tsx
  src/Pages/Home.tsx
  src/Utils/Constants/MockUp.tsx
  src/Utils/Constants/Storage.tsx
Labels: Feat

#15 Feat: date 받는 로직 모듈화
  src/Components/Nav/Nav.tsx
  src/Utils/Constants/Date.tsx
  src/Utils/GetDate.tsx
Labels: Feat, Status: Review 요청

#19 Feat 필터링 기능 구현
  src/Components/TodoList/TodoFilter.tsx
  src/Components/TodoList/TodoItem.tsx
  src/Components/TodoList/TodoList.tsx
  src/Components/TodoList/Utils/TodoService.tsx
  src/Components/TodoList/Utils/filtering.ts
  src/Pages/Home.tsx
Labels: Status: Review 요청

#20 Feat/to do item
  package-lock.json
  src/Components/TodoList/TodoItem.tsx
  src/Components/TodoList/TodoList.tsx
  src/Pages/Home.tsx
  yarn.lock
Labels: Feat
